# File generated by CompCert 3.5
# Command line: b.c -S -o b.s
	.text
	.align	16
	.globl f
f:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movq	%rbx, 8(%rsp)
	movq	%rdi, %rbx
	testl	%ebx, %ebx
	jne	.L100
	xorl	%eax, %eax
	jmp	.L101
.L100:
	leal	-1(%ebx), %edi
	call	g
	leal	0(%eax,%ebx,1), %eax
.L101:
	movq	8(%rsp), %rbx
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	f, @function
	.size	f, . - f
