# File generated by CompCert 3.5
# Command line: static_b.c -S
	.data
	.align	4
memoized:
	.long	0
	.long	0
	.type	memoized, @object
	.size	memoized, . - memoized
	.text
	.align	16
	.globl g
g:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movq	%rbx, 8(%rsp)
	movq	%rdi, %rbx
	testl	%ebx, %ebx
	jne	.L100
	xorl	%eax, %eax
	jmp	.L101
.L100:
	movl	memoized(%rip), %eax
	cmpl	%eax, %ebx
	je	.L102
	leal	-1(%ebx), %edi
	call	f
	leal	0(%eax,%ebx,1), %eax
	movl	%ebx, memoized(%rip)
	movl	%eax, (memoized + 4)(%rip)
	jmp	.L101
.L102:
	movl	(memoized + 4)(%rip), %eax
.L101:
	movq	8(%rsp), %rbx
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	g, @function
	.size	g, . - g
